delete veNTA_CLIENTE
delete COMPRA_ARTICULO
delete COMPRA
delete NOTA_CREDITO
delete VENTA_ARTICULO
delete VENTA
delete PAGO_CLIENTE
delete CLIENTE where IDCLIE>0
delete STOCK
delete MOVIMIENTO
DELETE RUBRO
delete ARTICULO
DELETE NOTA_CREDITO
delete CIERRECAJA
delete CAJA

DBCC CHECKIDENT (COMPRA, reseed, 0)
DBCC CHECKIDENT (ARTICULO, reseed, 0)
DBCC CHECKIDENT (MOVIMIENTO, reseed, 0)
DBCC CHECKIDENT (CLIENTE, reseed, 1)
DBCC CHECKIDENT (PAGO_CLIENTE, reseed, 0)
DBCC CHECKIDENT (STOCK, reseed, 0)
DBCC CHECKIDENT (VENTA, reseed, 0)
DBCC CHECKIDENT (rubro, reseed, 0)
DBCC CHECKIDENT (cierrecaja, reseed, 0)
DBCC CHECKIDENT (caja, reseed, 0)