

/****** Object:  Table [dbo].[INTERES]    Script Date: 07/04/2023 09:33:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INTERES](
	[RubroId] [numeric](3, 0) NULL,
	[TipoPagoId] [smallint] NULL,
	[PorcInteres] [decimal](18, 2) NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[INTERES]  WITH CHECK ADD  CONSTRAINT [FK_INTERES_RUBRO] FOREIGN KEY([RubroId])
REFERENCES [dbo].[RUBRO] ([CODIRUBR])
GO

ALTER TABLE [dbo].[INTERES] CHECK CONSTRAINT [FK_INTERES_RUBRO]
GO

ALTER TABLE [dbo].[INTERES]  WITH CHECK ADD  CONSTRAINT [FK_INTERES_TIPO_PAGO] FOREIGN KEY([TipoPagoId])
REFERENCES [dbo].[TIPO_PAGO] ([IDTIPA])
GO

ALTER TABLE [dbo].[INTERES] CHECK CONSTRAINT [FK_INTERES_TIPO_PAGO]
GO


