CREATE TABLE [dbo].[TIPO_PAGO](
	[IDTIPA] [smallint] NOT NULL,
	[NOMBRETIPA] [varchar](65) NULL,
	[ELIMINADOTIPA] BIT DEFAULT 0,
 CONSTRAINT [PK_TIPO_PAGO] PRIMARY KEY CLUSTERED 
(
	[IDTIPA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


