ALTER PROCEDURE [dbo].[SPventaPorFechaVend] (
	@F1 AS SMALLDATETIME,
	@F2 AS SMALLDATETIME
)
AS

   select NUMEVTA as 'N° Remito',FECHVTA as 'Fecha', LETRAVTA 'Letra' , TOTAVTA as 'Total',TIPOVTA, V.TIPOPAGOVTA, TP.NOMBRETIPA 
   from VENTA V
   INNER JOIN TIPO_PAGO TP ON V.TIPOPAGOVTA=TP.IDTIPA
   WHERE (FECHVTA >=@F1 AND FECHVTA <=@F2)
   AND ELIMINADOVTA=0
   ORDER BY FECHVTA

