/****** Object:  Table [dbo].[ORIGENDESTINO_CAJA]    Script Date: 25/02/2021 08:24:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORIGENDESTINO_CAJA](
	[IDODC] [int] NOT NULL,
	[TIPOODC] [smallint] NULL,
	[NOMBREODC] [varchar](100) NULL,
	[ELIMINADOODC] [bit] NULL CONSTRAINT [DF_ORIGENDESTINO_CAJA_ELIMINADOODC]  DEFAULT ((0)),
 CONSTRAINT [PK_ORIGENDESTINO_CAJA] PRIMARY KEY CLUSTERED 
(
	[IDODC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ORIGENDESTINO_CAJA]  WITH CHECK ADD  CONSTRAINT [FK_ORIGENDESTINO_CAJA_TIPOORIGENDESTINO_CAJA] FOREIGN KEY([TIPOODC])
REFERENCES [dbo].[TIPOORIGENDESTINO_CAJA] ([IDTODC])
GO

ALTER TABLE [dbo].[ORIGENDESTINO_CAJA] CHECK CONSTRAINT [FK_ORIGENDESTINO_CAJA_TIPOORIGENDESTINO_CAJA]
GO


