/****** Object:  Table [dbo].[CAJA]    Script Date: 25/02/2021 08:23:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CAJA](
	[IDCAJA] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FECHACAJA] [datetime] NULL,
	[NROFACTCAJA] [varchar](20) NULL,
	[TIPOCAJA] [bit] NULL,
	[ORIDESCAJA] [int] NULL,
	[DETALLECAJA] [varchar](200) NULL,
	[SUBTOTALCAJA] [decimal](18, 2) NULL,
	[PORCIVACAJA] [decimal](18, 2) NULL,
	[IVACAJA] [decimal](18, 2) NULL,
	[TOTALCAJA] [decimal](18, 2) NULL,
	[ELIMINADOCAJA] [bit] NULL CONSTRAINT [DF_CAJA_ELIMINADOCAJA]  DEFAULT ((0)),
	[TIPOCTACAJA] [bit] NULL DEFAULT ((0)),
 CONSTRAINT [PK_CAJA] PRIMARY KEY CLUSTERED 
(
	[IDCAJA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CAJA]  WITH CHECK ADD  CONSTRAINT [FK_CAJA_ORIGENDESTINO_CAJA] FOREIGN KEY([ORIDESCAJA])
REFERENCES [dbo].[ORIGENDESTINO_CAJA] ([IDODC])
GO

ALTER TABLE [dbo].[CAJA] CHECK CONSTRAINT [FK_CAJA_ORIGENDESTINO_CAJA]
GO


