
/****** Object:  StoredProcedure [dbo].[SPcierreCajaAgregar]    Script Date: 27/02/2021 10:47:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPcierreCajaAgregar] (
	@EFECTIVO DECIMAL(18,2),
	@TARJCREDITO DECIMAL(18,2),
	@TARJDEBITO  DECIMAL(18,2),
	@MERCADOPAGO  DECIMAL(18,2),
	@CTACTE  DECIMAL(18,2),
	@SALDO  DECIMAL(18,2),
	@TOTALVTA  DECIMAL(18,2),
	@TOTALNC  DECIMAL(18,2),
	@INGRESOS  DECIMAL(18,2),
	@EGRESOS  DECIMAL(18,2),
	@RET INT OUTPUT
)
AS
INSERT INTO CIERRECAJA (FECHACICA,EFECTIVOCICA,TARJCREDITOCICA,TARJDEBITOCICA,CTACTECICA,SALDOCICA,TOTALVTACICA,TOTALNOTACREDITOCICA,INGRESOSCAJACICA,EGRESOSCAJACICA,MERCADOPAGOCICA)
VALUES (GETDATE(),@EFECTIVO,@TARJCREDITO,@TARJDEBITO,@CTACTE,@SALDO,@TOTALVTA,@TOTALNC,@INGRESOS,@EGRESOS,@MERCADOPAGO)

SET @RET = @@IDENTITY

GO


