/****** Object:  Table [dbo].[CIERRECAJA]    Script Date: 27/02/2021 10:49:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CIERRECAJA](
	[IDCICA] [int] IDENTITY(1,1) NOT NULL,
	[FECHACICA] [datetime] NULL,
	[EFECTIVOCICA] [decimal](18, 2) NULL,
	[TARJCREDITOCICA] [decimal](18, 2) NULL,
	[TARJDEBITOCICA] [decimal](18, 2) NULL,
	[MERCADOPAGOCICA] [decimal](18, 2) NULL,
	[CTACTECICA] [decimal](18, 2) NULL,
	[SALDOCICA] [decimal](18, 2) NULL,
	[TOTALVTACICA] [decimal](18, 2) NULL,
	[TOTALNOTACREDITOCICA] [decimal](18, 2) NULL,
	[INGRESOSCAJACICA] [decimal](18, 2) NULL,
	[EGRESOSCAJACICA] [decimal](18, 2) NULL,
 CONSTRAINT [PK_CIERRECAJA] PRIMARY KEY CLUSTERED 
(
	[IDCICA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


