
/****** Object:  Table [dbo].[CONDICIONIVA]    Script Date: 05/03/2021 08:15:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONDICIONIVA](
	[IDCIVA] [smallint] NOT NULL,
	[NOMBRECIVA] [varchar](50) NULL,
	[ELIMINADOCIVA] [bit] NULL CONSTRAINT [DF_CONDICIONIVA_ELIMINADOCIVA]  DEFAULT ((0)),
 CONSTRAINT [PK_CONDICIONIVA] PRIMARY KEY CLUSTERED 
(
	[IDCIVA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


