/****** Object:  Table [dbo].[VENTA_ART_ADICIONALES]    Script Date: 25/05/2021 19:47:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VENTA_ART_ADICIONALES](
	[ID] [numeric](18, 0) NOT NULL,
	[PORCDTO] [decimal](18, 2) NULL,
 CONSTRAINT [PK_VENTA_ART_ADICIONALES_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VENTA_ART_ADICIONALES]  WITH CHECK ADD  CONSTRAINT [FK_VENTA_ART_ADICIONALES_VENTA_ARTICULO] FOREIGN KEY([ID])
REFERENCES [dbo].[VENTA_ARTICULO] ([IDVEAR])
GO

ALTER TABLE [dbo].[VENTA_ART_ADICIONALES] CHECK CONSTRAINT [FK_VENTA_ART_ADICIONALES_VENTA_ARTICULO]
GO


