create procedure RptStockMinimo
AS
select A.* 
from ARTICULO a
INNER JOIN RUBRO R ON A.RUBRARTI=R.CODIRUBR
INNER JOIN MARCA M ON A.MARCAARTI=M.IDMARC
where STOCKARTI<=STOCKMINARTI and ESTAARTI=0 
order by R.DESCRUBR, M.NOMBREMARC,A.DESCARTI
